### ISSUE TITLE
Lỗi khi nhập 2 số điện thoại trở lên

### ISSUE THREAD

**Issue by volong1012** [nukeviet/module-organs#3]
Trong phần "Thêm nhân sự" mục điện thoại phần di động (nếu điền 2 số trở lên và ngăn cách nhau bằng dấu - (chưa biết các dấu khác ra sao) thì sẽ bị báo lỗi )

**Comment by hoaquynhtim99** [comment]
@volong1012 anh kiểm tra bản mới nhất còn lỗi không nhé, nếu còn tạo giùm em issue mới
